//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeiXinStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class instruments
    {
        public int InstrumentId { get; set; }
        public int InstrumentNum { get; set; }
        public string InstrumentName { get; set; }
        public string InstrumentDescribe { get; set; }
        public Nullable<double> Instrumentprice { get; set; }
        public string Img1 { get; set; }
        public string Img2 { get; set; }
        public string Img3 { get; set; }
        public string Img4 { get; set; }
        public string Img5 { get; set; }
        public string Img6 { get; set; }
        public string ProductImg { get; set; }
    }
}
